Refactoring code on MainActivity
usekamba/kamba-android-sdk pull request #14
Opened 2019-02-19 15:36 UTC by EngCorreia

modified:  adicionei um metodo com nome  initVerification,para verificar se o merchantId ="" ou secretId ="" ou se environment= "SANDBOX" app/src/main/java/com/usekamba/kamba_payments_sdk/MainActivity.java

Nestas classes apenas ouve modificação nos espaço 👍 

   modified:   kamba-android-sdk/src/main/java/com/usekamba/kambapaysdk/core/HmacSha1.java
        modified:   kamba-android-sdk/src/main/java/com/usekamba/kambapaysdk/core/requests/CheckoutTransactionBuilder.java

2019-02-19 21:44 UTC, AlexJuca requested changes
A validação das informações para autenticação do comerciante devem ser feitas na própria lib e não no cliente. Actualmente o cliente que implementa a lib está fazendo essa validação que não é correcto, isso aumenta a complexidade para quem vai integrar a nossa lib, a lib deve ser responsavél por isso não o cliente. A classe responsável por isso é ClientConfig e é lá onde devem ser feitas essas validações.

2019-02-20 08:37 UTC, EngCorreia commented
está bem alexandre vou tratar disso

Em ter, 19 de fev de 2019 às 22:44, Alexandre Antonio Juca <
notifications@github.com> escreveu:

> *@AlexJuca* requested changes on this pull request.
>
> A validação das informações para aunteticação do comerciante devem ser
> feitas na própria lib e não no cliente. Actualmente o cliente que
> implementa a lib está fazendo essa validação que não é correcto, isso
> aumenta a complexidade para quem vai integrar a nossa lib, a lib deve ser
> responsavél por isso não o cliente. A classe responsável por isso é
> ClientConfig e é lá onde devem ser feitas essas validações.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/usekamba/kamba-android-sdk/pull/14#pullrequestreview-205468167>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AoI7Xz38TMYfz8F0adtQVmzKo7rTUVL4ks5vPHAkgaJpZM4bDPhu>
> .
>

2019-02-20 11:17 UTC, EngCorreia commented
removi a autenticação do lado cliente, implementei a autenticação na classe ClientConfig e organizei o codigo da classe MainActivity

2019-02-20 11:23 UTC, AlexJuca requested changes
Deve ser validado o ambiente. Neste caso ou ambiente só poderá ser PRODUCTION ou SANDBOX. 

Se não for um destes então deve retornar um IllegalStateException.

2019-02-21 09:50 UTC, merged